version: '3'
services:
  db_transaction_system:
    image: postgres:16.2-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: transaction_system_user
      POSTGRES_PASSWORD: transaction_system_password
      POSTGRES_DB: transaction_system
    ports:
      - "5432:5432"
    volumes:
      - ./.build/pgdata:/var/lib/postgresql/data
    networks:
      - transaction-system

  transaction_system_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transaction-system-api
    ports:
      - "8080:8080"
    environment:
      - GO111MODULE=on
    networks:
      - transaction-system
    depends_on:
      - db_transaction_system


networks:
  transaction-system:
    driver: bridge