basePath: /
definitions:
  dtos.GetAccountByIdOutputDTO:
    properties:
      account_id:
        type: integer
      document_number:
        type: string
    type: object
  response.ExceptionResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  description: App to handle with transactions routine
  title: Transaction System API
  version: "1.0"
paths:
  /accounts/{id}:
    get:
      consumes:
      - application/json
      description: get account by id
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.GetAccountByIdOutputDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ExceptionResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ExceptionResponse'
      summary: Get Account by Id
swagger: "2.0"
